#!/usr/bin/env python3
"""
バイナリファイルを C# コードに埋め込むツール
"""

import sys
from pathlib import Path


def embed_binary(binary_path: Path) -> str:
    """バイナリファイルを読み込んで、C# コードとして埋め込む"""
    data = binary_path.read_bytes()

    # バイト配列リテラルを生成（80文字ごとに改行）
    byte_lines = []
    bytes_per_line = 16
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i:i+bytes_per_line]
        byte_str = ", ".join(f"0x{b:02x}" for b in chunk)
        byte_lines.append(f"        {byte_str}")

    byte_array = ",\n".join(byte_lines)

    # C# コードを生成
    return f"""// <auto-generated/>
// このファイルは Tools/embed_binary.py によって自動生成されています

using System;

namespace Tsumiki.View.Mac;

internal static partial class ShaderLibrary
{{
    public static ReadOnlySpan<byte> MetalLibraryData =>
    [
{byte_array}
    ];
}}
"""


def main():
    """メイン関数"""
    if len(sys.argv) != 2:
        print("Usage: embed_binary.py <binary_file>", file=sys.stderr)
        sys.exit(1)

    binary_path = Path(sys.argv[1])
    if not binary_path.exists():
        print(f"Error: {binary_path} not found", file=sys.stderr)
        sys.exit(1)

    cs_code = embed_binary(binary_path)
    print(cs_code)


if __name__ == "__main__":
    main()
