#!/usr/bin/env python3
"""
PNG 画像を Brotli 圧縮して C# コードに埋め込むツール
"""

import sys
import brotli
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Install with: pip3 install Pillow", file=sys.stderr)
    sys.exit(1)


def generate_load_method(png_path: Path, method_name: str) -> str:
    """PNG 画像を読み込んで、C# のロードメソッドを生成する"""
    # PNG を RGBA に変換
    img = Image.open(png_path).convert('RGBA')
    width, height = img.size
    pixels = img.tobytes()  # RGBA バイトデータ

    # RGBA → BGRA 変換（Metal と DirectX で使用される形式）
    bgra = bytearray(len(pixels))
    for i in range(0, len(pixels), 4):
        bgra[i] = pixels[i+2]     # B
        bgra[i+1] = pixels[i+1]   # G
        bgra[i+2] = pixels[i]     # R
        bgra[i+3] = pixels[i+3]   # A

    # Brotli 圧縮
    compressed = brotli.compress(bytes(bgra), quality=11)

    # 圧縮率を表示
    compression_ratio = len(compressed) / len(bgra) * 100
    print(f"  {png_path.name}: {len(bgra)} bytes → {len(compressed)} bytes ({compression_ratio:.1f}%)")

    # C# バイト配列リテラルを生成（80文字ごとに改行）
    byte_lines = []
    bytes_per_line = 16
    for i in range(0, len(compressed), bytes_per_line):
        chunk = compressed[i:i+bytes_per_line]
        byte_str = ", ".join(f"0x{b:02x}" for b in chunk)
        byte_lines.append(f"            {byte_str}")

    byte_array = ",\n".join(byte_lines)

    # C# メソッドコードを生成
    return f"""    public static unsafe void {method_name}(nint rendererHandle)
    {{
        const int width = {width};
        const int height = {height};

        ReadOnlySpan<byte> compressed =
        [
{byte_array}
        ];

        var decompressed = new byte[width * height * 4];
        using (var decoder = new System.IO.Compression.BrotliDecoder())
        {{
            decoder.Decompress(compressed, decompressed, out _, out _);
        }}

        fixed (byte* ptr = decompressed)
        {{
            MacInterop.tsumiki_renderer_load_texture(rendererHandle, (nint)ptr, width, height);
        }}
    }}
"""


def main():
    """メイン関数"""
    # パス設定
    project_root = Path(__file__).parent.parent
    resources_dir = project_root / "Tsumiki.View.Mac" / "Resources"
    output_file = resources_dir / "ImageResource.g.cs"

    # PNG ファイル
    images = {
        "LoadMain": resources_dir / "Main.png",
        "LoadMod": resources_dir / "Mod.png",
        "LoadTuning": resources_dir / "Tuning.png",
    }

    # ファイルの存在確認
    for method_name, png_path in images.items():
        if not png_path.exists():
            print(f"Error: {png_path} not found", file=sys.stderr)
            sys.exit(1)

    print("Generating image resources...")

    # 各画像のロードメソッドを生成
    methods = []
    for method_name, png_path in images.items():
        methods.append(generate_load_method(png_path, method_name))

    # C# ファイルを生成
    cs_code = f"""// <auto-generated/>
// このファイルは Tools/generate_image_resources.py によって自動生成されています

using System;

namespace Tsumiki.View.Mac.Resources;

public static partial class ImageResource
{{
{chr(10).join(methods)}
}}
"""

    # ファイルに書き込み
    output_file.write_text(cs_code, encoding='utf-8')
    print(f"Generated: {output_file}")
    print(f"Total size: {output_file.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
